---
# yamllint disable rule:line-length
name: Build and release

on:
  pull_request:
    types: [opened, reopened, synchronize]
  push:
    branches:
      - master
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: i686
          cc: 0

      - name: Build
        run: |
          CXX_COMPILER=g++-9 make dummyengine
          make dummyengine.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 7
          name: binaries
          path: |
            dummyengine
            dummyengine.exe

  release:
    name: Release
    if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: binaries

      - name: Release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            dummyengine
            dummyengine.exe
